def listarProductos():
    print("Lista de productos")
    print("1. Coca cola")
    print("2. Cheetos")
    print("3. Maruchan")
    print("4. Palomitas")
    print("5. Gomitas")
    print("6. Fruta")
    print("7. Verdura")
    print("8. Helado")
    print("9. Papel higiénico")
    print("10. Yogurth griego")