def listarEspecialidades():
    print("Especialidades")
    print("1. Medicina familiar")
    print("2. Medicina preventiva")
    print("3. Urgencias")
    print("4. Tococirugia")
    print("5. Nutrición y dietética")
    print("6. Estomatología")
    print("7. Psicología")
    print("8. Trabajo social")
    print("9. Cardiología")
    print("10. Cirugía general")
    print("11. Ginecología y obstretricia")
    print("12. Infectología")
    print("13. Neurocirugía")
    print("14. Ortopedia")
    print("15. Pediatría")
    print("16. Urología")
    print("17. Psiquiatría")
    print("18. Gatroenterología")
    print("19. Otorrinolaringología")
    print("20. Laboratorios")